"use client";

import Link from "next/link";
import { ReactNode } from "react";

export function PageShell({ title, subtitle, children, actions, eyebrow = "ARAMBH WORKSPACE" }: { title: string; subtitle?: string; children?: ReactNode; actions?: ReactNode; eyebrow?: string }) {
  return <section className="page-shell mx-auto max-w-[1440px] px-4 py-6 sm:px-7 sm:py-8"><div className="page-heading"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1>{subtitle ? <p className="page-subtitle">{subtitle}</p> : null}</div>{actions ? <div className="page-actions">{actions}</div> : null}</div><div className="mt-7">{children}</div></section>;
}
export function EmptyState({ message, action }: { message: string; action?: ReactNode }) { return <div className="empty-state"><div className="empty-state-mark" aria-hidden="true">—</div><p>{message}</p>{action}</div>; }
export function LoadingState({ label = "Loading your workspace…" }: { label?: string }) { return <div className="sih-loading"><span className="loading-dot" aria-hidden="true" />{label}</div>; }
export function StatusBadge({ status }: { status: string }) { const value = String(status || "recommended").replace(/_/g, " "); const tone = /completed|live|high|critical/.test(value) ? "success" : /progress|enrolled|medium|simulated/.test(value) ? "info" : /dismissed|down|low/.test(value) ? "muted" : "warning"; return <span className={`status-badge status-${tone}`}><span className="status-dot" aria-hidden="true" />{value}</span>; }
export function MetricCard({ label, value, hint, tone = "blue", icon }: { label: string; value: string | number; hint?: string; tone?: string; icon?: string }) { return <div className={`metric-card metric-${tone}`}><div className="metric-card-top"><span className="metric-icon" aria-hidden="true">{icon || "•"}</span><span className="metric-label">{label}</span></div><strong>{value}</strong>{hint ? <p>{hint}</p> : null}</div>; }
export const StatCard = MetricCard;
export function SectionCard({ title, eyebrow, action, children, className = "" }: { title: string; eyebrow?: string; action?: ReactNode; children: ReactNode; className?: string }) { return <section className={`section-card ${className}`}><div className="section-card-heading">{eyebrow ? <p className="eyebrow">{eyebrow}</p> : null}<div className="section-card-title"><h2>{title}</h2>{action}</div></div>{children}</section>; }
export function ProgressBar({ value, target = 100, tone = "blue" }: { value: number; target?: number; tone?: string }) { const percent = Math.max(0, Math.min(100, target ? (value / target) * 100 : 0)); return <div className="progress-track" role="progressbar" aria-valuenow={value} aria-valuemin={0} aria-valuemax={target}><span className={`progress-fill progress-${tone}`} style={{ width: `${percent}%` }} /></div>; }
export function DomainCard({ name, current, target, count }: { name: string; current: number; target?: number; count: number }) { return <div className="domain-card"><div className="domain-card-head"><div><p className="eyebrow">Domain</p><h3>{name}</h3></div><strong>{current.toFixed(1)}<small>/5</small></strong></div><ProgressBar value={current} target={target || 5} /><div className="domain-card-meta"><span>{count} competencies</span><span>{target ? `Target ${target.toFixed(1)}` : "Current level"}</span></div></div>; }
export function Journey({ steps }: { steps: { label: string; detail: string; active?: boolean }[] }) { return <div className="journey" aria-label="Learning journey">{steps.map((step, index) => <div className={`journey-step ${step.active ? "is-active" : ""}`} key={step.label}><span className="journey-number">{String(index + 1).padStart(2, "0")}</span><div><strong>{step.label}</strong><p>{step.detail}</p></div>{index < steps.length - 1 ? <span className="journey-line" aria-hidden="true" /> : null}</div>)}</div>; }
export function SihNavLink({ href, children }: { href: string; children: ReactNode }) { return <Link href={href as never} className="sih-inline-link">{children}</Link>; }
