"use client";
import { useEffect, useState } from "react";
import { RoleGate } from "@/components/RoleGate";
import { DomainCard, EmptyState, Journey, LoadingState, MetricCard, PageShell, ProgressBar, SectionCard, StatusBadge } from "@/components/sih/ui";
import { api } from "@/lib/api";

const LEVELS: Record<number, string> = { 0: "Not assessed", 1: "Beginner", 2: "Basic", 3: "Intermediate", 4: "Advanced", 5: "Expert" };
const isMapped = (score: any) => score.targetLevelSource === "role_requirement" || score.targetLevelSource === "career_requirement";

export default function CompetenciesPage() { return <RoleGate roles={["employee"]}><CompetenciesContent /></RoleGate>; }

function CompetenciesContent() {
  const [scores, setScores] = useState<any[]>([]); const [message, setMessage] = useState<string>(); const [loading, setLoading] = useState(true); const [query, setQuery] = useState(""); const [domain, setDomain] = useState("all");
  useEffect(() => { api.get("/competencies/me").then((res) => { setScores(res.data.scores || []); setMessage(res.data.message); }).finally(() => setLoading(false)); }, []);
  const assessed = scores.filter((s) => (s.currentLevel || 0) > 0 || s.lastAssessedAt); const avg = assessed.length ? assessed.reduce((sum, score) => sum + (score.currentLevel || 0), 0) / assessed.length : null; const mappedScores = scores.filter(isMapped); const target = mappedScores.length ? mappedScores.reduce((sum, score) => sum + (score.targetLevel || 0), 0) / mappedScores.length : null;
  const filtered = scores.filter((s) => { const label = String(s.competencyId?.name || ""); const d = String(s.competencyId?.domain || s.competencyId?.category || ""); return label.toLowerCase().includes(query.toLowerCase()) && (domain === "all" || d.toLowerCase().includes(domain.toLowerCase())); });
  const domains = ["Statistical", "Technical", "Digital Governance", "Behavioural / Managerial"].map((name) => { const rows = scores.filter((s) => String(s.competencyId?.domain || s.competencyId?.category || "").toLowerCase().includes(name.split(" ")[0].toLowerCase())); return { name, rows, current: rows.length ? rows.reduce((sum, s) => sum + (s.currentLevel || 0), 0) / rows.length : 0 }; });
  if (loading) return <PageShell title="Competency profile"><LoadingState /></PageShell>;
  return <PageShell title="Competency profile" subtitle="Understand your current capability through assessment, practical and learning evidence." actions={<a href="/assessments" className="sih-button-primary">Take assessment</a>}>
    <div className="metric-grid"><MetricCard label="Competencies tracked" value={scores.length} hint="Across the ARAMBH framework" icon="◌" /><MetricCard label="With evidence" value={assessed.length} hint="Assessed or practically evidenced" tone="green" icon="✓" /><MetricCard label="Average current level" value={avg == null ? "—" : avg.toFixed(1)} hint="Out of 5" tone="blue" icon="◎" /><MetricCard label="Average target level" value={target == null ? "—" : target.toFixed(1)} hint="Configured role requirement" tone="orange" icon="↑" /></div>
    <SectionCard title="Domain overview" eyebrow="CAPABILITY LANDSCAPE" className="mt-5"><div className="domain-grid">{domains.map((d) => <DomainCard key={d.name} name={d.name} current={d.current} count={d.rows.length} />)}</div>{!scores.length ? <EmptyState message={message || "No competency data. Save your profile first."} /> : null}</SectionCard>
    {scores.length ? <SectionCard title="Current versus target" eyebrow="DETAILED EVIDENCE" className="mt-5"><div className="filter-bar"><label className="search-field"><span aria-hidden="true">⌕</span><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search competencies" aria-label="Search competencies" /></label><select className="sih-field" value={domain} onChange={(e) => setDomain(e.target.value)} aria-label="Filter competencies"><option value="all">All domains</option>{domains.map((d) => <option key={d.name} value={d.name}>{d.name}</option>)}</select></div><div className="competency-list">{filtered.map((s) => { const current = s.currentLevel || 0; const mapped = isMapped(s); const required = mapped ? s.targetLevel : current; const gap = mapped ? Math.max(0, required - current) : 0; const confidence = s.confidence || "low"; const evidence = s.evidenceSummary || s.evidence?.slice(-1)[0]?.detail || "No evidence recorded"; return <div className="competency-row" key={s._id}><div className="competency-name"><strong>{s.competencyId?.name || "—"}</strong><span>{s.competencyId?.domain || s.competencyId?.category || "Competency"}</span></div><div className="competency-level"><div><b>{current}</b><span>{LEVELS[current] || current}</span></div><ProgressBar value={current} target={required} /></div><div className="competency-target"><span>Target</span><b>{mapped ? required : "No mapped requirement"}</b></div><div className="competency-gap"><span>Gap</span><b>{mapped ? gap : "—"}</b></div><div><StatusBadge status={confidence} />{s.evidence && s.evidence.length > 0 ? <div className="mt-3"><Journey steps={s.evidence.map((e: any) => ({ label: e.type || "Evidence", detail: `${e.detail || "Recorded"} (${new Date(e.at).toLocaleDateString()})`, active: true }))} /></div> : <p className="row-detail">{evidence}</p>}</div></div>; })}{!filtered.length ? <EmptyState message="No competencies match these filters." /> : null}</div></SectionCard> : null}
  </PageShell>;
}
