"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { RoleGate } from "@/components/RoleGate";
import { EmptyState, LoadingState, MetricCard, PageShell, ProgressBar, SectionCard, StatusBadge } from "@/components/sih/ui";
import { api } from "@/lib/api";
export default function SkillGapsPage() { return <RoleGate roles={["employee"]}><SkillGapsContent /></RoleGate>; }
function SkillGapsContent() {
  const [gaps, setGaps] = useState<any[]>([]); const [message, setMessage] = useState<string>(); const [loading, setLoading] = useState(true);
  async function load() { setLoading(true); try { const { data } = await api.get("/skill-gaps/me"); setGaps(data.gaps || []); setMessage(data.message); } finally { setLoading(false); } }
  useEffect(() => { load(); }, []); async function refresh() { setLoading(true); try { const { data } = await api.post("/skill-gaps/refresh"); setGaps(data.gaps || []); setMessage(undefined); } finally { setLoading(false); } }
  const average = gaps.length ? gaps.reduce((s, g) => s + (Number(g.gap) || 0), 0) / gaps.length : 0; const priorities = ["critical", "high", "medium", "low"]; const counts = priorities.map((p) => ({ p, count: gaps.filter((g) => String(g.priority).toLowerCase() === p).length })); const max = Math.max(...counts.map((x) => x.count), 1);
  return <PageShell title="Skill-gap intelligence" subtitle="See where your current evidence is below the requirement for your role, and choose the next action." actions={<button onClick={refresh} className="sih-button-primary" disabled={loading}>Recalculate gaps</button>}>
    <div className="metric-grid"><MetricCard label="Critical gaps" value={counts[0].count} hint="Address these first" tone="red" icon="!" /><MetricCard label="High priority" value={counts[1].count} hint="Important role capabilities" tone="orange" icon="↑" /><MetricCard label="Medium priority" value={counts[2].count} hint="Plan into your path" tone="blue" icon="•" /><MetricCard label="Average gap" value={gaps.length ? average.toFixed(1) : "—"} hint="Levels below requirement" tone="violet" icon="∿" /></div>
    {loading ? <div className="mt-5"><LoadingState label="Loading your gap analysis…" /></div> : gaps.length === 0 ? <div className="mt-5"><EmptyState message={message || "No skill-gap records. Set a job role in Profile first."} /></div> : <>
      <div className="dashboard-grid mt-5"><SectionCard title="Priority distribution" eyebrow="WHERE TO FOCUS"><div className="bar-chart">{counts.map(({ p, count }) => <div className="bar-chart-row" key={p}><div><span>{p}</span><b>{count}</b></div><ProgressBar value={count} target={max} tone={p === "critical" ? "red" : p === "high" ? "orange" : "blue"} /></div>)}</div></SectionCard><SectionCard title="Domain signals" eyebrow="PATTERN ACROSS CAPABILITIES"><div className="compact-list">{Object.entries(gaps.reduce((acc: Record<string, number>, g: any) => { const domain = g.competencyId?.domain || g.competencyId?.category || "Unclassified"; acc[domain] = (acc[domain] || 0) + (Number(g.gap) || 0); return acc; }, {})).sort((a: any, b: any) => b[1] - a[1]).map(([name, total]) => <div className="compact-list-row" key={name}><div><strong>{name}</strong><span>Combined gap across recorded competencies</span></div><b>{Number(total).toFixed(1)}</b></div>)}</div></SectionCard></div>
      <SectionCard title="Priority gap list" eyebrow="DECISION SUPPORT" className="mt-5"><div className="gap-list">{gaps.map((g) => { const current = Number(g.currentLevel) || 0; const required = Number(g.requiredLevel) || 0; return <article className={`gap-card gap-${String(g.priority || "medium").toLowerCase()}`} key={g._id}><div className="gap-card-main"><div><StatusBadge status={g.priority || "medium"} /><h3>{g.competencyId?.name || "Competency"}</h3><p>{g.competencyId?.domain || g.competencyId?.category || "Capability area"}</p></div><div className="gap-number"><strong>{g.gap ?? "—"}</strong><span>level gap</span></div></div><div className="gap-card-data"><span>Current <b>{current}</b></span><span>Required <b>{required}</b></span><span>Confidence <b>{g.confidence || "low"}</b></span><span>Evidence <b>{g.evidenceSummary || "Not recorded"}</b></span></div><div className="gap-card-action"><span>{g.recommendedAction || g.rationale || "Review the learning path for a relevant action."}</span><Link href="/learning-path" className="sih-button-secondary">View learning path →</Link></div></article>; })}</div></SectionCard>
    </>}
  </PageShell>;
}
